events/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='event_index'),
    path('event/<str:event_url>', views.event_detail, name='event_detail'),
    path('event/confirmation/', views.event_confirmation, name='event_confirmation'),
    path('event/confirmation/<str:registration_number>', views.event_confirmation, name='event_confirmation'),
    path('event/payment/handoff/<str:registration_number>', views.paymnet_handoff, name='paymnet_handoff'),
    path('event/payment/<str:registration_number>', views.event_payment_complete, name='event_payment_complete'),
]

heinz_signup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from heinz_signup.settings import DJANGO_HOST

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/', include('event_management.urls')),
    path('', include('events.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'events.views.handler404'
handler500 = 'events.views.handler500'

'''
Django Auth URLS:

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']

'''
# shibboleth URLs if in prod
if DJANGO_HOST == 'prod':
    urlpatterns += [
        url(r'^shib/', include('shibboleth.urls', namespace='shibboleth')),
    ]

events/models.py
import datetime

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from ckeditor.fields import RichTextField

from heinz_signup.settings import MEDIA_ROOT, DATE_INPUT_FORMATS

DB_PREFIX = 'hz_events_'


class CommonField(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    trash = models.BooleanField(default=False)

    class Meta:
        abstract = True

    @property
    def is_active(self):
        return self.active

    @property
    def is_trash(self):
        return self.trash

    def flip_active_flag(self):
        if self.active:
            self.active = False
        else:
            self.active = True

    def flip_trash_flag(self):
        if self.trash:
            self.trash = False
        else:
            self.trash = True


class EventForm(CommonField):
    name = models.CharField(max_length=50)
    form_name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        db_table = DB_PREFIX + 'event_form'
        ordering = ['name']


class StoreFront(CommonField):
    name = models.CharField(max_length=50)
    storefront_url = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        db_table = DB_PREFIX + 'store_front'
        ordering = ['name']


allowed_guest_choices = (
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
)


class ManagementGroup(CommonField):
    name = models.CharField(max_length=50)
    members = models.TextField()

    def __str__(self):
        return '%s' % self.name

    class Meta:
        db_table = DB_PREFIX + 'management_group'
        ordering = ['name']


class Event(CommonField):
    # validator for url - alphnumeric, dash, underscore only)
    alphanumeric = RegexValidator(r'^[A-Za-z0-9_-]+$',
                                  'Only alphanumeric, dash, and underscore characters are allowed.')

    name = models.CharField(max_length=110)
    url = models.CharField(max_length=20, unique=True, validators=[alphanumeric])
    start_date = models.DateField()
    start_time = models.TimeField(max_length=12)
    end_date = models.DateField(blank=True, null=True)
    end_time = models.TimeField(max_length=12, blank=True, null=True)
    location_name = models.CharField(max_length=200)
    location_address = models.CharField(max_length=500)
    location_map_url = models.CharField(max_length=1000, blank=True, null=True)
    signup_start = models.DateField(blank=True, null=True)
    signup_by = models.DateField(blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    confirmation_text = RichTextField(blank=True, null=True)
    refund_policy = RichTextField(blank=True, null=True)
    contact_name = models.CharField(max_length=75)
    contact_email = models.EmailField(max_length=255)
    event_image = models.ImageField(upload_to='', blank=True, null=True)
    event_form = models.ForeignKey(EventForm, on_delete=models.PROTECT,
                                   limit_choices_to={'active': True, 'trash': False})
    storefront = models.ForeignKey(StoreFront, on_delete=models.SET_NULL, blank=True, null=True,
                                   limit_choices_to={'active': True, 'trash': False})
    storefront_itemcode = models.CharField(max_length=50, blank=True, null=True)
    fee = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    group = models.ForeignKey(ManagementGroup, on_delete=models.SET_NULL, blank=True, null=True)
    max_capacity = models.IntegerField(default=0)
    allowed_guest = models.IntegerField(default=0, choices=allowed_guest_choices)
    show_registration_barcode = models.BooleanField(default=False)
    show_form_only = models.BooleanField(default=False)

    def __str__(self):
        return '%s: %s' % (self.name, self.start_date)

    class Meta:
        db_table = DB_PREFIX + 'event'
        ordering = ['start_date', 'name']

    @property
    def get_total_collected(self):
        return Attendee.objects.filter(active=True, trash=False, event=self).annotate(Sum('registration_paid'))

    @property
    def get_total_attendee_count(self):

        # get count of attendees
        attendees = Attendee.objects.filter(active=True, trash=False, event=self)
        attendee_count = attendees.count()
        # get count of guests
        guest_count = attendees.aggregate(models.Sum('guests'))
        # calculate total attendance
        if guest_count['guests__sum'] is None:
            guest_count['guests__sum'] = 0

        attendee_total_count = attendee_count + guest_count['guests__sum']

        return attendee_total_count

    @property
    def is_at_capacity(self):
        # assume the event is full
        at_capacity = True

        attendee_total_count = self.get_total_attendee_count

        # zero means unlimited capacity, or attendee count has not reached max capacity
        if self.max_capacity == 0 or attendee_total_count < self.max_capacity:
            at_capacity = False

        return at_capacity

    @property
    def is_signup_open(self):
        event_open = True
        if self.signup_start:
            if self.signup_start >= timezone.now().date():
                event_open = False
        if self.signup_by:
            if self.signup_by <= timezone.now().date():
                event_open = False

        return event_open

    # @property
    # def is_past_signup_by_date(self):
    #     if self.signup_by >= timezone.now().date():
    #         return False
    #     else:
    #         return True
    #
    # @property
    # def is_today_signup_date(self):
    #     if self.signup_by == timezone.now().date():
    #         return True
    #     else:
    #         return False


guest_choices_0 = [
    (0, '0'),
]

guest_choices_1 = [
    (0, '0'),
    (1, '1'),
]

guest_choices_2 = [
    (0, '0'),
    (1, '1'),
    (2, '2'),
]

guest_choices_3 = [
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
]

guest_choices_4 = [
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
]

REGISTRATION_TYPE_CHOICES = (
    ('Current Student', 'Student'),
    ('Alumni', 'Alumni'),
    ('Faculty', 'Faculty'),
    ('Staff', 'Staff'),
    ('Admitted Heinz Student', 'Admitted Heinz Student'),
    ('Prospective Heinz Student', 'Prospective Heinz Student'),
)

AFFILIATION_CHOICES = (
    ('College of Engineering', 'College of Engineering'),
    ('College of Fine Arts', 'College of Fine Arts'),
    ('Dietrich College of Humanities & Social Sciences', 'Dietrich College of Humanities & Social Sciences'),
    ('Heinz College of Information Systems and Public Policy','Heinz College of Information Systems and Public Policy'),
    ('Mellon College of Science', 'Mellon College of Science'),
    ('School of Computer Science', 'School of Computer Science'),
    ('Tepper School of Business', 'Tepper School of Business'),
    ('Other', 'Other'),
)


class Attendee(CommonField):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    title = models.CharField(max_length=200, blank=True, null=True)
    organization = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=255)
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    registration_number = models.UUIDField()
    phone = models.CharField(max_length=50, blank=True, null=True)
    guests = models.IntegerField(default=0, choices=guest_choices_4) # set choices to max number allowed
    guests_name = models.CharField(max_length=500, blank=True, null=True, verbose_name='Guest Name(s)')
    dietary_needs = models.CharField(max_length=50, default='', blank=True, null=True)
    registration_date = models.DateTimeField(blank=True, null=True)
    registration_fee = models.IntegerField(blank=True, null=True)
    registration_paid = models.IntegerField(blank=True, null=True)
    return_from_payment_portal = models.DateTimeField(blank=True, null=True)
    email_sent = models.DateField(blank=True, null=True)
    transaction_number = models.CharField(max_length=255, blank=True, null=True)
    registration_type = models.CharField(max_length=30, default='Other', choices=REGISTRATION_TYPE_CHOICES)
    registration_type_other = models.CharField(max_length=30, blank=True, null=True)
    affiliation = models.CharField(max_length=150, default='Other', choices=AFFILIATION_CHOICES)
    affiliation_other = models.CharField(max_length=150, blank=True, null=True)
    heinz_degree_program = models.CharField(max_length=255, blank=True, null=True)
    graduation_year = models.CharField(max_length=4, blank=True, null=True)
    street_1 = models.CharField(max_length=255, blank=True, null=True)
    street_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return '%s: %s, %s' % (self.event.name, self.last_name, self.first_name)

    class Meta:
        db_table = DB_PREFIX + 'attendee'
        ordering = ['last_name', 'first_name']

ELEMENT_TYPE_CHOICES = (
    ('CharField', 'Alphanumeric'),
    ('IntegerField', 'Integer'),
    ('TextField', 'Text Field'),
    ('BooleanField', 'Check Box'),
    ('DateField', 'Date'),
)


# models for managing signup form elements
class FormElements(CommonField):
    name = models.CharField(max_length=30)
    label = models.CharField(max_length=30)

templates/events/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Font Family -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/custom_public.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    {% block head-extra %}{% endblock head-extra %}
</head>
<body>
    <div id="container-fluid">
        <div class="row">
            {% include 'events/header.html' %}
{#            <div class="col-12 cmu-black-bg">#}
{#                <div class="header"></div>#}
{#            </div>#}
        </div>
        <div class="row">
            <div class="col-12">
                <div class="spacer10"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                {% block content %}{% endblock content %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="spacer10"></div>
            </div>
        </div>
    </div><!-- container -->
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/events/confirmation.html
{% extends 'events/base.html' %}
{% block head-extra %}{% endblock head-extra %}
{% block page_title %}{{ title }}{% endblock page_title %}
{% block content %}

    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card">
                <h2 class="card-header cmu_red_bg text-white">Registration Confirmation</h2>
                <div class="card-body">
                    <h1 class="cmu_red_text cmu-h1">{{ event.name}}</h1>
                    <h4 class="card-title">{{ event.start_date|date:'F j, Y' }} at {{ event.start_time}}
                        {% if event.end_date %} to {{ event.end_date|date:'F j, Y' }} {% if event.end_time %} at {{ event.end_time }} {% endif %}

                        {% elif event.end_time %}
                            until {{ event.end_time }}
                        {% endif %}
                    </h4>
                    <p class="card-text">
                        <p>{{ event.location_name }}<br/>{{ event.location_address }}</p>
{#                        {{ event.description|safe }}<br /><br />#}
                        <b>Registration ID</b>: {{ registration.registration_number }}<br />
                        <b>Registration Date</b>: {{ registration.registration_date|date:"SHORT_DATE_FORMAT" }}<br /><br />
                        <b>Attendee Information:</b><br/>
                        {{ registration.first_name }} {{ registration.last_name }}<br />
                        {% if registration.institution %}{{ registration.institution }}<br />{% endif %}
                        {% if registration.phone %}
                            {{ registration.phone }}<br/>
                        {% endif %}
                        {{ registration.email }}<br /><br />
                        {% if registration.dietary_needs %}<b>Dietary Needs</b>: {{ registration.dietary_needs }}<br /><br />{% endif %}
                        {% if registration.guests %}
                            <b>Guest Attending</b>: {{ registration.guests }}<br/>
                            <b>Guest Name(s)</b>: {{ registration.guests_name }}
                        {% endif %}
                        <br/><br/>

                        {% if event.fee %}
                            <b>Registration Fee</b><br/>
                            <table class="table">
                                <thread>
                                    <tr>
                                        <th scope="col">Description</th>
                                        <th scope="col">Item Total</th>
                                    </tr>
                                </thread>
                                <tbody>
                                    <tr>
                                        <td>Registration:</td>
                                        <td>${{ registration.registration_fee }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total Paid:</td>
                                        <td>${{ registration.registration_paid}}</td>
                                    </tr>
                                    <tr>
                                        <td>Balance:</td>
                                        <td>${{ balance }}</td>
                                    </tr>
                                </tbody>
                            </table>
                            <h3>Refunds</h3>
                            {%  if event.refund_policy %}
                                <p>{{ event.refund_policy|safe }}</p>
                            {% else %}
                                <p>For refunds, please contact <a href="mailto:{{ event.contact_email }}">{{ event.contact_name }}</a>.</p>
                            {% endif %}
                        {% else %}
                            <b>Registration Fee</b>: Free
                        {% endif %}
                        <br/><br/>
                        {% if event.confirmation_text %}
                            {{ event.confirmation_text|safe }}
                        {% else %}
                            <p>Thank you for registering for the {{ event.name }}. We look forward to seeing you.</p>
                            <p>To make changes to your registration, please contact <a href="mailto:{{ event.contact_email }}">{{ event.contact_name }}</a>.</p>
                            <p>We will send you an email confirmation shortly.</p>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>

{% endblock content %}

templates/events/email.html
{% extends 'events/base_email.html' %}
{% block head-extra %}{% endblock head-extra %}
{% block content %}

        <h1 class="cmu_red_text cmu-h1">{{ event.name}}</h1>
        {{ event.start_date|date:'F j, Y' }} at {{ event.start_time}}
        {% if event.end_date %} to {{ event.end_date|date:'F j, Y' }} {% if event.end_time %} at {{ event.end_time }} {% endif %}

        {% elif event.end_time %}
            until {{ event.end_time }}
        {% endif %}

        <p>{{ event.location_name }}<br/>{{ event.location_address }}</p>
        <b>Registration ID</b>: {{ registration.registration_number }}<br />
        <b>Registration Date</b>: {{ registration.registration_date|date:"SHORT_DATE_FORMAT" }}<br /><br />
        <b>Attendee Information:</b><br/>
        {{ registration.first_name }} {{ registration.last_name }}<br />
        {% if registration.institution %}{{ registration.institution }}<br />{% endif %}
        {% if registration.phone %}
            {{ registration.phone }}<br/>
        {% endif %}
        {{ registration.email }}<br /><br />
        {% if registration.dietary_needs %}<b>Dietary Needs</b>: {{ registration.dietary_needs }}<br /><br />{% endif %}
        {% if registration.guests %}
            <b>Guest Attending</b>: {{ registration.guests }}<br/>
            <b>Guest Name(s)</b>: {{ registration.guests_name }}
        {% endif %}
        <br/><br/>

        {% if event.fee %}
            <b>Registration Fee</b>:<br/>
            <table class="table">
                <tbody>
                    <tr>
                        <td>Registration:</td>
                        <td>${{ registration.registration_fee }}</td>
                    </tr>
                    <tr>
                        <td>Total Paid:</td>
                        <td>${{ registration.registration_paid}}</td>
                    </tr>
                    <tr>
                        <td>Balance:</td>
                        <td>${{ balance }}</td>
                    </tr>
                </tbody>
            </table>
            <h3>Refunds</h3>
            {%  if event.refund_policy %}
                <p>{{ event.refund_policy|safe }}</p>
            {% else %}
                <p>For refunds, please contact <a href="mailto:{{ event.contact_email }}">{{ event.contact_name }}</a>.</p>
            {% endif %}
        {% else %}
            <b>Registration Fee</b>: Free
        {% endif %}
        <br/><br/>
        {% if event.confirmation_text %}
            {{ event.confirmation_text|safe }}
        {% else %}
            <p>Thank you for registering for the {{ event.name }}. We look forward to seeing you.</p>
            <p>To make changes to your registration, please contact <a href="mailto:{{ event.contact_email }}">{{ event.contact_name }}</a>.</p>
            <p>We will send you an email confirmation shortly.</p>
        {% endif %}


{% endblock content %}

templates/events/generic_event_confirmation.html
{% extends 'reg_base/base.html' %}
{% block head-extra %}{% endblock head-extra %}
{% block page_title %}{{ title }}{% endblock page_title %}
{% block content %}
    <div class="col-2"></div>
    <div class="col-8">
        <h2>{{ page_title }}</h2>
        <p>
            Registration ID: {{ registration.registration_number }}<br />
            Registration Date: {{ registration.registration_date|date:"SHORT_DATE_FORMAT" }}<br /><br />
            {{ registration.first_name }} {{ registration.last_name }}<br />
            {{ registration.institution }}<br />
            {{ registration.email }}<br /><br />
            Attending reception on May 23rd: {% if registration.reception %} Yes {% else %} No {% endif %}<br />
            Attending dinner on May 24th: {% if registration.dinner %} Yes {% else %} No {% endif %}<br />
            Dietary Needs: {{ registration.dietary_needs }}<br /><br />
            <table class="table">
                <thread>
                    <tr>
                        <th scope="col">Description</th>
                        <th scope="col">Item Total</th>
                    </tr>
                </thread>
                <tbody>
                    <tr>
                        <td>Registration: {{ registration.get_registration_type_display }}</td>
                        <td>${{ registration.registration_fee }}</td>
                    </tr>
                    <tr>
                        <td>Total Paid:</td>
                        <td>${{ registration.registration_paid}}</td>
                    </tr>
                    <tr>
                        <td>Balance:</td>
                        <td>${{ balance }}</td>
                    </tr>
                </tbody>
            </table>
        <p>
            Thank you for registering for the {{ header_title }}. We look forward to seeing you in Pittsburgh, PA.
            Visitor information including parking and maps, can be found on the <a href="https://www.cmu.edu/visit/maps-parking-transportation.html">Carnegie Mellon University Visitors site</a>.
        </p>
        <p>
            To make changes to your registration, please contact <a href="mailto:pstraw@andrew.cmu.edu">Alessandro Acquisti</a>.
        </p>
        <p>
            We will send you an email confirmation shortly.
        </p>
        <h3>Refunds</h3>
        <p>If you have to cancel your paid registration, you will get 80% back until 30 days before the start of the event. In all other cases, the financial responsibilities of the participant remain fully effective. To cancel your registration, please contact <a href="mailto:pstraw@andrew.cmu.edu">Tricia Straw</a></p>
    </div>
    <div class="col-2"></div>
{% endblock content %}

templates/events/handoff.html
{% extends 'events/base.html' %}
{% load staticfiles %}
{% block page_title %}{{ title }}{% endblock page_title %}
{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">
                        <h1 class="cmu_red_text cmu-h1">{{ event.name}}</h1>
                        <hr class="hr hr--small">
                        <h6 class="cmu_red_text cmu-h6">WHEN</h6>
                        <p>{{ event.start_date|date:'F j, Y' }}</p>
                        <p>{{ event.start_time}}
                            {% if event.end_time %}
                                - {{ event.end_time }}
                            {% endif %}</p>
                        <h6 class="cmu_red_text cmu-h6">WHERE</h6>
                        <p>{{ event.location_name }}</p>
                        <p>{{ event.location_address }} {% if event.location_map_url %} <a class="cmu_red_text" href="{{ event.location_map_url }}">(map)</a>{% endif %}</p>
                        <h6 class="cmu_red_text cmu-h6">PAYMENT</h6>
                            <b>Total Attendees</b>: {{ total_attendee }}<br/>
                            <b>Total Cost</b>: ${{ total_cost }} (${{ event.fee }} per attendee)<br/><br/>
                        <form method="post" id="form1" enctype=multipart/form-data action="{{ storefront_url }}">
                            {% load crispy_forms_tags %}
                            {% crispy form %}
                        </form>

                    </p>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>


{% endblock content %}